### PR TITLE
VPN GW Az SKU

### PR DESCRIPTION
**Pull request by luisfarin**
Changed VPN GW SKU to avoid deployment error "Standard Public IPs associated with VPN gateways with non-AZ VPN skus cannot have zones configured"

### CODE REVIEW

**Comment by luisfarin** [comment]
Avoid "Standard Public IPs associated with VPN gateways with non-AZ VPN skus cannot have zones configured"

**Comment by nicolgit** [comment]
tutto ok

**Comment by joblini** [comment]
This commit seems to have broken the scenario for Spoke to Spoke connectivity using a VPN Gateway :
https://github.com/nicolgit/hub-and-spoke-playground/blob/main/scenarios/ping-any-to-any-gateway.md

I was able to revert to the **VpnGw1** SKU by creating the IP address using the **2020-08-01** api version, which creates a non-zonal IP by default:  `vnetGatewayIP 'Microsoft.Network/publicIPAddresses@2020-08-01' `

**Comment by nicolgit** [comment]
@joblini I have opened #21 to check this

**Pull request merged**
